SELECT DEPT_CODE,MIN(BASIC) AS MIN_BASIC,MAX(BASIC) AS MAX_BASIC,AVG(BASIC) AS AVG_BASIC FROM EMP GROUP BY DEPT_CODE;

SELECT DEPT_CODE,COUNT(*) AS FEMALE_NUM FROM EMP WHERE SEX='F' GROUP BY DEPT_CODE;

SELECT CITY,DEPT_CODE,COUNT(*) FROM EMP GROUP BY CITY,DEPT_CODE;

SELECT DESIG_CODE,DEPT_CODE ,COUNT(*) AS C FROM EMP WHERE YEAR(JN_DT)=2022GROUP BY DESIG_CODE,DEPT_CODE ORDER BY C;

SELECT DEPT_CODE,SUM(BASIC) AS SUM_BASIC FROM EMP WHERE SEX='M' GROUP BY DEPT_CODE HAVING SUM(BASIC) > 1000000  ORDER BY SUM_BASIC;

SELECT EMP.EMP_NAME,EMP.BASIC,DESIGNATION.DESIG_DESC FROM EMP INNER JOIN DESIGNATION ON EMP.DESIG_CODE = DESIGNATION.DESIG_CODE;

SELECT EMP.EMP_NAME,EMP.BASIC,DESIGNATION.DESIG_DESC,DEPARTMENT.DEPT_NAME FROM EMP, DESIGNATION, DEPARTMENT WHERE EMP.DESIG_CODE = DESIGNATION.DESIG_CODE AND EMP.DEPT_CODE= DEPARTMENT.DEPT_CODE;

/*SELECT DEPT_CODE FROM DEPARTMENT MINUS SELECT DISTINCT DEPT_CODE FROM EMP*/

SELECT DE.DEPT_CODE FROM DEPARTMENT DE WHERE (SELECT COUNT(*) FROM EMP WHERE EMP.DEPT_CODE=DE.DEPT_CODE) = 0;

SELECT DE.DEPT_CODE FROM DEPARTMENT DE WHERE (SELECT COUNT(*) FROM EMP WHERE EMP.DEPT_CODE=DE.DEPT_CODE) >= 1;

SELECT DE.DEPT_CODE FROM DEPARTMENT DE WHERE (SELECT COUNT(*) FROM EMP WHERE EMP.DEPT_CODE=DE.DEPT_CODE) >= 10;

SELECT DEPT_CODE FROM EMP WHERE BASIC=(SELECT MAX(BASIC) FROM EMP);

SELECT DEPT_CODE,COUNT(*) FROM EMP WHERE DESIG_CODE='MGR' GROUP BY DEPT_CODE;

SELECT MIN(-1*BASIC)*-1 AS MAX_BASIC FROM EMP

SELECT MAX(-1*BASIC)*-1 AS MIN_BASIC FROM EMP

SELECT A.DEPT_CODE,MAX(A.MAX_BASIC) FROM (SELECT MAX(BASIC),DEPT_CODE AS MAX_BASIC FROM EMP GROUP BY DEPT_CODE) AS A;

SELECT COUNT(*) FROM EMP WHERE SEX='F' AND DESIG_CODE='MGR';

INSERT INTO EMP(
    EMP.EMP_CODE,
    EMP.EMP_NAME,
    EMP.DEPT_CODE,
    EMP.DESIG_CODE,
    EMP.SEX,
    EMP.ADDRESS,
    EMP.CITY,
    EMP.[STATE],
    EMP.PIN,
    EMP.BASIC
)

VALUES

('008','AMANDA','PURC','NOT_P','F','21L GREEN STREET','KOLKATA','WB','81',1200000),
('009','MICHELE','FINC','NOT_P','F','27P MART STREET','KOLKATA','WB','97',1700000),
('010','NATE','PURC','NOT_P','M','L7 GREL STREET','HARIDWAR','UP','80',1400000);

/*SELECT * FROM EMP WHERE NOT EXISTS (SELECT DESIG_CODE FROM DESIGNATION WHERE DESIGNATION.DESIG_CODE=EMP.DESIG_CODE);*/

DELETE FROM EMP WHERE NOT EXISTS (SELECT DESIG_CODE FROM DESIGNATION WHERE DESIGNATION.DESIG_CODE=EMP.DESIG_CODE);

SELECT * FROM EMP E,(SELECT DEPT_CODE,AVG(BASIC) AVG_BASIC FROM EMP GROUP BY DEPT_CODE) E1 WHERE E.DEPT_CODE=E1.DEPT_CODE AND E.BASIC>E1.AVG_BASIC AND SEX='F';

SELECT COUNT(EMP_NAME) FROM EMP WHERE EMP.SEX='F' AND EMP.DESIG_CODE='HLPR'; 


